-- configure statusline for VSCode
-- return {
--   'nvim-lualine/lualine.nvim',
--   opts = {
--     dependencies = { 'nvim-tree/nvim-web-devicons' },
--     sections = {
--       lualine_a = { 'mode' },
--       lualine_b = {},
--       lualine_c = {},
--       lualine_x = {},
--       lualine_y = {},
--       lualine_z = {},
--     },
--     component_separators = { left = '', right = '' },
--     section_separators = { left = '', right = '' },
--     options = {
--       theme = 'auto',
--     },
--   },
-- }
return {}
